void rt(float *cameras, int d1, int f1, float *lights, int d2, int f2,
                int *obj_type, int obj_num0,
                float *obj_pos, int obj_num1, int d3,
                float *obj_param1, int obj_num1b, int d3b,
                float *obj_rot, int obj_num1c, int d3c,
                float *obj_amb, int obj_num2, int d4,
                float *obj_diff, int obj_num3, int d5,
                float *obj_spec, int obj_num4, int d6,
                float *obj_size, int obj_num5,
                float *obj_shine, int obj_num6,
                float *obj_refl, int obj_num7,
                float *obj_transparency, int obj_num8,
                float *obj_ior, int obj_num9,
                float *pixels, int n, int m,
                float *pix_loc, int n1, int d7);